/v1/sixr/casbin/get	GET
/v1/sixr/casbin/permission/@	GET
/v1/*/block/getByNum/@	GET
/v1/*/block/getByHash/@	GET
/v1/*/block/maxBlock	GET
/v1/*/block/query	POST
/v1/*/tx/get/@	GET
/v1/*/tx/query	POST
/v1/*/tx/getByAddr	POST
/v1/*/tx/amount	GET
/v1/*/tx/getAmountAddr/@	GET			
/v1/*/contract/getByAddr/@	GET
/v1/*/contract/getTxAmount/@	GET
/v1/*/contract/amount	GET
/v1/*/contract/query	POST
/v1/*/contract/token/query	POST
/v1/*/contract/holder	POST
/v1/*/contract/balance/top/holder	POST
/v1/*/contract/getToken	POST
/v1/*/contract/addedToken/info	POST
/v1/*/contract/data/decode/@	GET
/v1/*/account/getByAddr/@	GET
/v1/*/erc20/getByHash/@	GET
/v1/*/erc20/query	POST
/v1/*/erc20/getAmountAddr/@	GET
/v1/*/relation/getByAddr/@	GET
/v1/*/relation/getRoot	GET
/v1/*/statistics/info/@	GET
/v1/*/statistics/tx	POST
/v1/*/statistics/holder/changes/@	GET
/v1/sixr/lpPool/query	POST
/v1/sixr/label/add	POST
/v1/sixr/label/get/@	GET
/v1/sixr/label/get	POST
/v1/sixr/label/get/tags/@	GET
/v1/sixr/casbin/role/@	GET
/v1/sixr/label/remove	POST
/v1/sixr/casbin/get	GET
/v1/sixr/casbin/permission/@	GET
/v1/*/block/getByNum/@	GET
/v1/*/block/getByHash/@	GET
/v1/*/block/maxBlock	GET
/v1/*/block/query	POST
/v1/*/tx/get/@	GET
/v1/*/tx/query	POST
/v1/*/tx/getByAddr	POST
/v1/*/tx/amount	GET
/v1/*/tx/getAmountAddr/@	GET
/v1/*/contract/getByAddr/@	GET
/v1/*/contract/getTxAmount/@	GET
/v1/*/contract/amount	GET
/v1/*/contract/query	POST
/v1/*/contract/token/query	POST
/v1/*/contract/holder	POST
/v1/*/contract/balance/top/holder	POST
/v1/*/contract/getToken	POST
/v1/*/contract/addedToken/info	POST
/v1/*/contract/data/decode/@	GET
/v1/*/account/getByAddr/@	GET
/v1/*/erc20/getByHash/@	GET
/v1/*/erc20/query	POST
/v1/*/erc20/getAmountAddr/@	GET
/v1/*/relation/getByAddr/@	GET
/v1/*/relation/getRoot	GET
/v1/*/statistics/info/@	GET
/v1/*/statistics/tx	POST
/v1/*/statistics/holder/changes/@	GET
/v1/sixr/lpPool/query	POST
/v1/sixr/label/add	POST
/v1/sixr/label/get/@	GET
/v1/sixr/label/get	POST
/v1/sixr/label/get/tags/@	GET
/v1/sixr/casbin/role/@	GET
/v1/sixr/label/remove	POST
/v1/sixr/casbin/get	GET
/v1/sixr/casbin/permission/@	GET
/v1/*/block/getByNum/@	GET
/v1/*/block/getByHash/@	GET
/v1/*/block/maxBlock	GET
/v1/*/block/query	POST
/v1/*/tx/get/@	GET
/v1/*/tx/query	POST
/v1/*/tx/getByAddr	POST
/v1/*/tx/amount	GET
/v1/*/tx/getAmountAddr/@	GET
/v1/*/contract/getByAddr/@	GET
/v1/*/contract/getTxAmount/@	GET
/v1/*/contract/amount	GET
/v1/*/contract/query	POST
/v1/*/contract/token/query	POST
/v1/*/contract/holder	POST
/v1/*/contract/balance/top/holder	POST
/v1/*/contract/getToken	POST
/v1/*/contract/addedToken/info	POST
/v1/*/contract/data/decode/@	GET
/v1/*/account/getByAddr/@	GET
/v1/*/erc20/getByHash/@	GET
/v1/*/erc20/query	POST
/v1/*/erc20/getAmountAddr/@	GET
/v1/*/relation/getByAddr/@	GET
/v1/*/relation/getRoot	GET
/v1/*/statistics/info/@	GET
/v1/*/statistics/tx	POST
/v1/*/statistics/holder/changes/@	GET
/v1/sixr/lpPool/query	POST
/v1/sixr/label/add	POST
/v1/sixr/label/get/@	GET
/v1/sixr/label/get	POST
/v1/sixr/label/get/tags/@	GET
/v1/sixr/casbin/role/@	GET
/v1/sixr/label/remove	POST
/v1/sixr/label/query	POST
/v1/sixr/address/get/tree/@	GET
/v1/sixr/label/query/tag	POST
/v1/sixr/label/group/query	GET
/v1/sixr/project/add	POST
/v1/sixr/project/query	POST
/v1/sixr/project/update	PUT
/v1/sixr/project/delete/@	DELETE
/v1/sixr/project/findById/@	GET
/v1/sixr/label/selectByProjectId/@	GET
/v1/sixr/label/classify/address	POST
/v1/sixr/label/user/personal/tag	GET
/v1/sixr/label/query/personal/tag	POST
/v1/sixr/user/query	POST
/v1/sixr/user/update	POST
/v1/sixr/roles	GET